import { 
  Sparkles, Wind, Droplets, Zap, Paintbrush, Bug, 
  Sofa, Bed, Hammer, ShieldCheck, Thermometer, FlaskConical,
  Gauge, Wrench, Plug, Droplet, Toilet, Pipette, Flame, 
  AlertTriangle, Container, Home, Building, Brush
} from 'lucide-react';

export const CATEGORY_PACKAGES = {
  cleaning: [
    {
      id: 'basic',
      name: 'Basic Home Cleaning',
      icon: Sparkles,
      desc: 'Standard cleaning for regular upkeep',
      scope: 'General wiping, sweeping, mopping',
      inclusions: ['Dust & wipe surfaces', 'Sweep & mop floors', 'Clean bathrooms', 'Empty trash'],
      duration: '2-4 hours',
      recommendedSize: 'Studio - 3BR Condo',
      price: 89,
      isPopular: false,
    },
    {
      id: 'deep',
      name: 'Deep Cleaning',
      icon: Droplets,
      desc: 'Top-to-bottom thorough cleaning',
      scope: 'Intensive cleaning reaching hidden corners.',
      inclusions: ['Inside cabinets', 'Appliance exteriors', 'Skirting boards', 'Window interiors', 'Everything in Basic'],
      duration: '4-8 hours',
      recommendedSize: 'Any property size',
      price: 299,
      isPopular: true,
    },
    {
      id: 'move',
      name: 'Move-In / Move-Out',
      icon: Home,
      desc: 'Full empty-home clean for handover',
      scope: 'Detailed cleaning for empty properties.',
      inclusions: ['Deep cleaning of all rooms', 'Inside all cabinets & drawers', 'Wall wiping (spot cleaning)', 'Window tracks'],
      duration: '5-8 hours',
      recommendedSize: 'Empty properties',
      price: 349,
      isPopular: false,
    },
    {
      id: 'post-reno',
      name: 'Post Renovation',
      icon: Hammer,
      desc: 'Heavy-duty dust and debris removal',
      scope: 'Specialized cleaning after construction.',
      inclusions: ['Fine dust removal', 'Paint splatter removal', 'Vacuuming & mopping multiple times', 'Deep bathroom scrub'],
      duration: '6-8 hours',
      recommendedSize: 'Newly renovated',
      price: 499,
      isPopular: false,
    },
    {
      id: 'kitchen',
      name: 'Kitchen Deep Cleaning',
      icon: Flame,
      desc: 'Grease and grime removal',
      scope: 'Focused deep cleaning for the kitchen only.',
      inclusions: ['Stove & hood degreasing', 'Inside fridge & oven', 'Sink sanitization', 'Cabinet exteriors'],
      duration: '2-3 hours',
      recommendedSize: 'All kitchens',
      price: 149,
      isPopular: false,
    },
    {
      id: 'bathroom',
      name: 'Bathroom Deep Cleaning',
      icon: Toilet,
      desc: 'Hard water stains and mold removal',
      scope: 'Focused deep cleaning for bathrooms.',
      inclusions: ['Grout scrubbing', 'Toilet descaling', 'Mirror polish', 'Shower glass water stains'],
      duration: '2 hours',
      recommendedSize: 'Up to 2 Bathrooms',
      price: 129,
      isPopular: false,
    },
    {
      id: 'sofa',
      name: 'Sofa Cleaning',
      icon: Sofa,
      desc: 'Fabric or leather sofa deep clean',
      scope: 'Extraction cleaning for couches.',
      inclusions: ['Vacuuming', 'Stain treatment', 'Deep extraction', 'Odor neutralization'],
      duration: '1-2 hours',
      recommendedSize: '3-seater sofa',
      price: 119,
      isPopular: false,
    },
    {
      id: 'mattress',
      name: 'Mattress Cleaning',
      icon: Bed,
      desc: 'UV + extraction clean',
      scope: 'Dust mite and stain removal.',
      inclusions: ['UV light treatment', 'Deep vacuuming', 'Steam cleaning', 'Stain removal'],
      duration: '1 hour',
      recommendedSize: 'Queen / King mattress',
      price: 99,
      isPopular: false,
    },
  ],
  ac: [
    {
      id: 'inspection',
      name: 'AC Inspection',
      icon: Thermometer,
      desc: 'Check and diagnose AC issues',
      scope: 'Diagnostic check for non-cooling or noisy ACs.',
      inclusions: ['Temperature test', 'Gas pressure check', 'Component inspection', 'Repair quotation'],
      duration: '30 mins',
      recommendedSize: 'Wall-mounted / Cassette',
      price: 50,
      isPopular: false,
    },
    {
      id: 'standard',
      name: 'Standard AC Service',
      icon: Wind,
      desc: 'Basic maintenance for cooling',
      scope: 'Filter washing and basic clearing.',
      inclusions: ['Filter wash', 'Coil dust-off', 'Drain pipe clearing', 'Performance check'],
      duration: '45 mins',
      recommendedSize: 'Wall-mounted 1.0 - 2.0 HP',
      price: 59,
      isPopular: false,
    },
    {
      id: 'chemical',
      name: 'Chemical Wash',
      icon: FlaskConical,
      desc: 'Deep clean for better airflow',
      scope: 'Intensive chemical wash to remove stubborn dirt.',
      inclusions: ['Chemical spray on coils', 'Blower cleaning', 'Drain pipe flushing', 'Anti-bacterial wipe'],
      duration: '1.5 hours',
      recommendedSize: 'AC not serviced > 6 months',
      price: 129,
      isPopular: true,
    },
    {
      id: 'overhaul',
      name: 'Chemical Overhaul',
      icon: Wrench,
      desc: 'Full dismantle and wash',
      scope: 'Complete breakdown of AC unit for deep chemical wash.',
      inclusions: ['Dismantle unit', 'Chemical soak', 'Bearing check & lube', 'Gas level check'],
      duration: '2-3 hours',
      recommendedSize: 'Severely clogged AC',
      price: 199,
      isPopular: false,
    },
    {
      id: 'gas',
      name: 'Gas Top-Up',
      icon: Gauge,
      desc: 'Refrigerant refill (R32/R410A)',
      scope: 'Restore cooling gas levels.',
      inclusions: ['Pressure reading', 'Gas top-up', 'Leak visual check', 'Cooling test'],
      duration: '45 mins',
      recommendedSize: 'Low cooling units',
      price: 149,
      isPopular: false,
    },
    {
      id: 'repair',
      name: 'AC Repair',
      icon: Wrench,
      desc: 'Fix leaks, noise, or power issues',
      scope: 'Targeted repair based on diagnosis.',
      inclusions: ['Part replacement (cost separate)', 'Leak patching', 'Testing & commissioning'],
      duration: 'Variable',
      recommendedSize: 'Any broken AC',
      price: 80,
      isPopular: false,
    },
  ],
  plumbing: [
    {
      id: 'leak',
      name: 'Leak Repair',
      icon: Droplets,
      desc: 'Fix dripping pipes or fixtures',
      scope: 'Identify and patch minor water leaks.',
      inclusions: ['Diagnosis', 'Pipe patching / tightening', 'Water flow test', 'Workmanship warranty'],
      duration: '1-2 hours',
      recommendedSize: 'Visible leaks',
      price: 99,
      isPopular: true,
    },
    {
      id: 'pipe',
      name: 'Pipe Replacement',
      icon: Wrench,
      desc: 'Replace old or burst pipes',
      scope: 'Install new PVC, UPVC or copper pipes.',
      inclusions: ['Remove old pipe', 'Install new pipe segment', 'Joint sealing', 'Pressure test'],
      duration: '2-4 hours',
      recommendedSize: 'Burst or rusted pipes',
      price: 150,
      isPopular: false,
    },
    {
      id: 'faucet',
      name: 'Faucet / Tap Installation',
      icon: Droplet,
      desc: 'Install or replace water taps',
      scope: 'Standard tap or mixer replacement.',
      inclusions: ['Remove old tap', 'Install new tap (client provided)', 'Teflon sealing', 'Leak test'],
      duration: '45 mins',
      recommendedSize: 'Kitchen & Bathrooms',
      price: 69,
      isPopular: false,
    },
    {
      id: 'toilet',
      name: 'Toilet Repair',
      icon: Toilet,
      desc: 'Fix flush or install new bowl',
      scope: 'Cistern repairs or full bowl replacement.',
      inclusions: ['Flush mechanism fix', 'Full seal replacement', 'Water level adjustment'],
      duration: '1-2 hours',
      recommendedSize: 'Running toilets',
      price: 120,
      isPopular: false,
    },
    {
      id: 'heater',
      name: 'Water Heater Repair',
      icon: Flame,
      desc: 'Fix instant or storage heaters',
      scope: 'Electrical/plumbing fix for heaters.',
      inclusions: ['Element check', 'Leak fix', 'Thermostat adjustment', 'Safety test'],
      duration: '1.5 hours',
      recommendedSize: 'No hot water / Leaks',
      price: 130,
      isPopular: false,
    },
    {
      id: 'drain',
      name: 'Drain Unclogging',
      icon: Pipette,
      desc: 'Clear blocked sinks or floor traps',
      scope: 'Remove blockages from pipes.',
      inclusions: ['Manual snaking', 'Chemical dissolving (if needed)', 'Flow test'],
      duration: '1 hour',
      recommendedSize: 'Slow draining water',
      price: 89,
      isPopular: false,
    },
    {
      id: 'emergency-plumbing',
      name: 'Emergency Plumbing',
      icon: AlertTriangle,
      desc: '24/7 urgent burst pipe fix',
      scope: 'Immediate dispatch for critical issues.',
      inclusions: ['90-min ETA', 'Main valve shutoff', 'Temporary or permanent fix', 'Priority routing'],
      duration: 'Variable',
      recommendedSize: 'Major flooding',
      price: 199,
      isPopular: false,
    },
  ],
  electrical: [
    {
      id: 'electrical-inspect',
      name: 'Electrical Inspection',
      icon: Zap,
      desc: 'Diagnose tripping or wiring issues',
      scope: 'Fault finding and safety check.',
      inclusions: ['DB board check', 'Circuit testing', 'Load calculation', 'Repair quote'],
      duration: '1 hour',
      recommendedSize: 'Tripping MCB/RCCB',
      price: 80,
      isPopular: false,
    },
    {
      id: 'socket',
      name: 'Socket Installation',
      icon: Plug,
      desc: 'Install new power points',
      scope: 'Add or replace 13A/15A sockets.',
      inclusions: ['Wiring extension (up to 3m)', 'Socket faceplate mounting', 'Earth loop test'],
      duration: '1-2 hours',
      recommendedSize: 'Per socket',
      price: 90,
      isPopular: true,
    },
    {
      id: 'light',
      name: 'Light Installation',
      icon: Sparkles,
      desc: 'Install downlights or fixtures',
      scope: 'Mounting and wiring of light fittings.',
      inclusions: ['Fixture mounting (client provided)', 'Wiring connection', 'Switch test'],
      duration: '45 mins',
      recommendedSize: 'Per light fixture',
      price: 60,
      isPopular: false,
    },
    {
      id: 'fan',
      name: 'Ceiling Fan Installation',
      icon: Wind,
      desc: 'Install ceiling or wall fans',
      scope: 'Safe mounting of fan units.',
      inclusions: ['Hook installation', 'Fan assembly', 'Balancing', 'Speed regulator setup'],
      duration: '1.5 hours',
      recommendedSize: 'Per fan',
      price: 75,
      isPopular: false,
    },
    {
      id: 'db-board',
      name: 'DB Board Service',
      icon: Zap,
      desc: 'Replace or upgrade distribution board',
      scope: 'Main electrical panel works.',
      inclusions: ['Breaker replacement', 'Load balancing', 'Cable tidying', 'Full safety test'],
      duration: '3-5 hours',
      recommendedSize: 'Old or unsafe boards',
      price: 350,
      isPopular: false,
    },
    {
      id: 'wiring',
      name: 'Wiring Repair',
      icon: Plug,
      desc: 'Fix burnt or faulty wiring',
      scope: 'Replace damaged cables.',
      inclusions: ['Fault tracing', 'Cable replacement', 'Conduit fixing', 'Continuity test'],
      duration: 'Variable',
      recommendedSize: 'Burnt smell / sparks',
      price: 150,
      isPopular: false,
    },
    {
      id: 'emergency-electrical',
      name: 'Emergency Electrical Service',
      icon: AlertTriangle,
      desc: '24/7 total blackout assistance',
      scope: 'Urgent restoration of power.',
      inclusions: ['90-min ETA', 'TNB coordination (if needed)', 'Temporary power bypass', 'Priority routing'],
      duration: 'Variable',
      recommendedSize: 'Total power loss',
      price: 200,
      isPopular: false,
    },
  ],
  painting: [
    {
      id: 'room',
      name: 'Room Painting',
      icon: Brush,
      desc: 'Paint a single bedroom',
      scope: 'Wall and ceiling painting for one room.',
      inclusions: ['Floor protection', 'Minor crack patching', '1 coat primer (optional)', '2 coats paint'],
      duration: '1 day',
      recommendedSize: 'Up to 150 sqft',
      price: 350,
      isPopular: false,
    },
    {
      id: 'interior',
      name: 'Interior Painting',
      icon: Home,
      desc: 'Full house interior',
      scope: 'Complete interior walls and ceilings.',
      inclusions: ['Furniture covering', 'Wall prep & sanding', '2 coats emulsion paint', 'Post-paint cleanup'],
      duration: '3-5 days',
      recommendedSize: 'Living + Bedrooms',
      price: 1200,
      isPopular: true,
    },
    {
      id: 'exterior',
      name: 'Exterior Painting',
      icon: Building,
      desc: 'Weather-resistant exterior coat',
      scope: 'Outer walls and facades.',
      inclusions: ['High-pressure wash prep', 'Fungus wash', 'Weatherbond primer', '2 coats exterior paint'],
      duration: '4-7 days',
      recommendedSize: 'Landed properties',
      price: 2500,
      isPopular: false,
    },
    {
      id: 'condo',
      name: 'Condo Repainting',
      icon: Building,
      desc: 'Specialized for high-rises',
      scope: 'Interior painting compliant with condo rules.',
      inclusions: ['Management permit assistance', 'Common area protection', 'Odorless paint options'],
      duration: '2-4 days',
      recommendedSize: '800 - 1500 sqft',
      price: 1500,
      isPopular: false,
    },
    {
      id: 'premium-paint',
      name: 'Premium Paint Package',
      icon: Sparkles,
      desc: 'Washable, anti-bacterial finish',
      scope: 'High-end paint application.',
      inclusions: ['Premium brand paint (e.g. Nippon Odour-less)', 'Flawless wall skimming', 'Color consultation'],
      duration: '4-6 days',
      recommendedSize: 'Luxury homes',
      price: 3000,
      isPopular: false,
    },
  ],
  'pest-control': [
    {
      id: 'general-pest',
      name: 'General Pest Treatment',
      icon: Bug,
      desc: 'Routine spraying for common pests',
      scope: 'Preventative surface spray.',
      inclusions: ['Perimeter spraying', 'Targeted crack & crevice treatment', 'Basic baiting'],
      duration: '1 hour',
      recommendedSize: 'Apartments / Condos',
      price: 99,
      isPopular: true,
    },
    {
      id: 'cockroach',
      name: 'Cockroach Treatment',
      icon: Bug,
      desc: 'Eradicate roach infestations',
      scope: 'Intensive baiting and flushing.',
      inclusions: ['Gel bait application', 'Flushing chemicals in drains', 'Kitchen cabinet treatment'],
      duration: '1.5 hours',
      recommendedSize: 'Active infestation',
      price: 150,
      isPopular: false,
    },
    {
      id: 'termite-inspect',
      name: 'Termite Inspection',
      icon: ShieldCheck,
      desc: 'Detect termite activity',
      scope: 'Professional assessment using scanners.',
      inclusions: ['Thermal imaging scan', 'Moisture meter check', 'Comprehensive report', 'Treatment quote'],
      duration: '1.5 hours',
      recommendedSize: 'Landed properties',
      price: 120,
      isPopular: false,
    },
    {
      id: 'termite-treat',
      name: 'Termite Treatment',
      icon: Hammer,
      desc: 'Soil treatment or baiting system',
      scope: 'Eliminate termite colonies.',
      inclusions: ['Drilling & chemical injection OR Baiting station setup', 'Colony elimination guarantee', 'Warranty certificate'],
      duration: '1 day',
      recommendedSize: 'Active termite damage',
      price: 1500,
      isPopular: false,
    },
    {
      id: 'rodent',
      name: 'Rodent Control',
      icon: Bug,
      desc: 'Rat and mouse trapping',
      scope: 'Baiting and exclusion work.',
      inclusions: ['Trap placement', 'Entry point sealing', 'Carcass removal (follow-up)'],
      duration: '2 visits',
      recommendedSize: 'Ceiling noises / droppings',
      price: 250,
      isPopular: false,
    },
    {
      id: 'mosquito',
      name: 'Mosquito Treatment',
      icon: Wind,
      desc: 'Fogging and larvicide',
      scope: 'Outdoor mosquito eradication.',
      inclusions: ['Thermal fogging', 'Larvicide in stagnant water', 'Drainage inspection'],
      duration: '1 hour',
      recommendedSize: 'Gardens / Outdoors',
      price: 180,
      isPopular: false,
    },
  ]
};

export const CATEGORY_ADDONS = {
  cleaning: [
    { id: 'extra_bathroom', label: 'Extra Bathroom', price: 25 },
    { id: 'window', label: 'Window Cleaning', price: 40 },
    { id: 'carpet', label: 'Carpet Vacuum', price: 30 },
    { id: 'ironing', label: 'Ironing (20 items)', price: 35 },
  ],
  ac: [
    { id: 'antibac', label: 'Anti-bacterial coating', price: 39 },
    { id: 'drain_pipe', label: 'Drain pipe replacement', price: 49 },
    { id: 'remote', label: 'Remote replacement', price: 55 },
  ],
  plumbing: [
    { id: 'braided_hose', label: 'Braided hose replacement', price: 25 },
    { id: 'warranty1y', label: '1-yr leak warranty', price: 49 },
    { id: 'patching', label: 'Wall patching', price: 45 },
  ],
  electrical: [
    { id: 'cable', label: 'Extra cable (per meter)', price: 15 },
    { id: 'casing', label: 'PVC casing', price: 20 },
  ],
  painting: [
    { id: 'primer', label: 'Apply 1 coat primer', price: 200 },
    { id: 'doors', label: 'Paint 3 interior doors', price: 150 },
  ],
  'pest-control': [
    { id: 'extra_bait', label: 'Extra gel baits', price: 30 },
    { id: 'followup', label: 'Follow-up visit (14 days)', price: 80 },
  ]
};

export function getPackages(serviceId) {
  const norm = serviceId === 'home-cleaning' ? 'cleaning' : 
               serviceId === 'ac-servicing' ? 'ac' : serviceId;
  return CATEGORY_PACKAGES[norm] || CATEGORY_PACKAGES.cleaning;
}

export function getAddons(serviceId) {
  const norm = serviceId === 'home-cleaning' ? 'cleaning' : 
               serviceId === 'ac-servicing' ? 'ac' : serviceId;
  return CATEGORY_ADDONS[norm] || CATEGORY_ADDONS.cleaning;
}
