import { 
  Sparkles, Wind, Droplets, Zap, Paintbrush, Bug, 
  Sofa, Bed, Hammer, ShieldCheck, Thermometer, FlaskConical,
  Gauge, Wrench, Plug, Droplet, Toilet, Pipette, Flame, 
  AlertTriangle, Container, Home, Building, Brush
} from 'lucide-react';

export const CATEGORY_PACKAGES = {
  cleaning: [
    {
      id: 'basic',
      name: 'Basic Home Cleaning',
      nameMy: 'Pembersihan Rumah Asas',
      icon: Sparkles,
      desc: 'Standard cleaning for regular upkeep',
      descMy: 'Pembersihan standard untuk penyelenggaraan berkala',
      scope: 'General wiping, sweeping, mopping',
      scopeMy: 'Mengelap, menyapu, dan mengemop secara am',
      inclusions: ['Dust & wipe surfaces', 'Sweep & mop floors', 'Clean bathrooms', 'Empty trash'],
      inclusionsMy: ['Buang habuk & lap permukaan', 'Sapu & mop lantai', 'Bersihkan bilik air', 'Buang sampah'],
      duration: '2-4 hours',
      durationMy: '2-4 jam',
      recommendedSize: 'Studio - 3BR Condo',
      recommendedSizeMy: 'Studio - Kondo 3 Bilik',
      price: 89,
      isPopular: false,
    },
    {
      id: 'deep',
      name: 'Deep Cleaning',
      nameMy: 'Pembersihan Mendalam',
      icon: Droplets,
      desc: 'Top-to-bottom thorough cleaning',
      descMy: 'Pembersihan menyeluruh dari atas ke bawah',
      scope: 'Intensive cleaning reaching hidden corners.',
      scopeMy: 'Pembersihan intensif sehingga ke sudut tersembunyi.',
      inclusions: ['Inside cabinets', 'Appliance exteriors', 'Skirting boards', 'Window interiors', 'Everything in Basic'],
      inclusionsMy: ['Dalam kabinet', 'Luaran peralatan', 'Papan skirting', 'Bahagian dalam tingkap', 'Semua dalam pakej Asas'],
      duration: '4-8 hours',
      durationMy: '4-8 jam',
      recommendedSize: 'Any property size',
      recommendedSizeMy: 'Sebarang saiz hartanah',
      price: 299,
      isPopular: true,
    },
    {
      id: 'move',
      name: 'Move-In / Move-Out',
      nameMy: 'Masuk / Keluar Rumah',
      icon: Home,
      desc: 'Full empty-home clean for handover',
      descMy: 'Pembersihan penuh rumah kosong untuk serahan',
      scope: 'Detailed cleaning for empty properties.',
      scopeMy: 'Pembersihan terperinci untuk hartanah kosong.',
      inclusions: ['Deep cleaning of all rooms', 'Inside all cabinets & drawers', 'Wall wiping (spot cleaning)', 'Window tracks'],
      inclusionsMy: ['Pembersihan mendalam semua bilik', 'Dalam semua kabinet & laci', 'Lap dinding (pembersihan setempat)', 'Landasan tingkap'],
      duration: '5-8 hours',
      durationMy: '5-8 jam',
      recommendedSize: 'Empty properties',
      recommendedSizeMy: 'Hartanah kosong',
      price: 349,
      isPopular: false,
    },
    {
      id: 'post-reno',
      name: 'Post Renovation',
      nameMy: 'Selepas Pengubahsuaian',
      icon: Hammer,
      desc: 'Heavy-duty dust and debris removal',
      descMy: 'Penyingkiran habuk dan serpihan berat',
      scope: 'Specialized cleaning after construction.',
      scopeMy: 'Pembersihan khusus selepas pembinaan.',
      inclusions: ['Fine dust removal', 'Paint splatter removal', 'Vacuuming & mopping multiple times', 'Deep bathroom scrub'],
      inclusionsMy: ['Penyingkiran habuk halus', 'Penyingkiran percikan cat', 'Vakum & mop berulang kali', 'Sental bilik air secara mendalam'],
      duration: '6-8 hours',
      durationMy: '6-8 jam',
      recommendedSize: 'Newly renovated',
      recommendedSizeMy: 'Baru diubah suai',
      price: 499,
      isPopular: false,
    },
    {
      id: 'kitchen',
      name: 'Kitchen Deep Cleaning',
      nameMy: 'Pembersihan Mendalam Dapur',
      icon: Flame,
      desc: 'Grease and grime removal',
      descMy: 'Penyingkiran gris dan kotoran',
      scope: 'Focused deep cleaning for the kitchen only.',
      scopeMy: 'Pembersihan mendalam khusus untuk dapur sahaja.',
      inclusions: ['Stove & hood degreasing', 'Inside fridge & oven', 'Sink sanitization', 'Cabinet exteriors'],
      inclusionsMy: ['Nyahgris dapur & tudung ekzos', 'Dalam peti sejuk & ketuhar', 'Sanitasi sinki', 'Luaran kabinet'],
      duration: '2-3 hours',
      durationMy: '2-3 jam',
      recommendedSize: 'All kitchens',
      recommendedSizeMy: 'Semua dapur',
      price: 149,
      isPopular: false,
    },
    {
      id: 'bathroom',
      name: 'Bathroom Deep Cleaning',
      nameMy: 'Pembersihan Mendalam Bilik Air',
      icon: Toilet,
      desc: 'Hard water stains and mold removal',
      descMy: 'Penyingkiran kesan air keras dan kulat',
      scope: 'Focused deep cleaning for bathrooms.',
      scopeMy: 'Pembersihan mendalam khusus untuk bilik air.',
      inclusions: ['Grout scrubbing', 'Toilet descaling', 'Mirror polish', 'Shower glass water stains'],
      inclusionsMy: ['Sental nat jubin', 'Nyahkerak tandas', 'Gilap cermin', 'Kesan air pada kaca pancuran'],
      duration: '2 hours',
      durationMy: '2 jam',
      recommendedSize: 'Up to 2 Bathrooms',
      recommendedSizeMy: 'Sehingga 2 Bilik Air',
      price: 129,
      isPopular: false,
    },
    {
      id: 'sofa',
      name: 'Sofa Cleaning',
      nameMy: 'Pembersihan Sofa',
      icon: Sofa,
      desc: 'Fabric or leather sofa deep clean',
      descMy: 'Pembersihan mendalam sofa fabrik atau kulit',
      scope: 'Extraction cleaning for couches.',
      scopeMy: 'Pembersihan ekstraksi untuk sofa.',
      inclusions: ['Vacuuming', 'Stain treatment', 'Deep extraction', 'Odor neutralization'],
      inclusionsMy: ['Vakum', 'Rawatan kotoran', 'Ekstraksi mendalam', 'Penyahbauan'],
      duration: '1-2 hours',
      durationMy: '1-2 jam',
      recommendedSize: '3-seater sofa',
      recommendedSizeMy: 'Sofa 3 tempat duduk',
      price: 119,
      isPopular: false,
    },
    {
      id: 'mattress',
      name: 'Mattress Cleaning',
      nameMy: 'Pembersihan Tilam',
      icon: Bed,
      desc: 'UV + extraction clean',
      descMy: 'Pembersihan UV + ekstraksi',
      scope: 'Dust mite and stain removal.',
      scopeMy: 'Penyingkiran hama habuk dan kotoran.',
      inclusions: ['UV light treatment', 'Deep vacuuming', 'Steam cleaning', 'Stain removal'],
      inclusionsMy: ['Rawatan cahaya UV', 'Vakum mendalam', 'Pembersihan wap', 'Penyingkiran kotoran'],
      duration: '1 hour',
      durationMy: '1 jam',
      recommendedSize: 'Queen / King mattress',
      recommendedSizeMy: 'Tilam Queen / King',
      price: 99,
      isPopular: false,
    },
  ],
  ac: [
    {
      id: 'inspection',
      name: 'AC Inspection',
      nameMy: 'Pemeriksaan AC',
      icon: Thermometer,
      desc: 'Check and diagnose AC issues',
      descMy: 'Semak dan diagnosis masalah AC',
      scope: 'Diagnostic check for non-cooling or noisy ACs.',
      scopeMy: 'Pemeriksaan diagnostik untuk AC yang tidak sejuk atau bising.',
      inclusions: ['Temperature test', 'Gas pressure check', 'Component inspection', 'Repair quotation'],
      inclusionsMy: ['Ujian suhu', 'Semakan tekanan gas', 'Pemeriksaan komponen', 'Sebut harga pembaikan'],
      duration: '30 mins',
      durationMy: '30 minit',
      recommendedSize: 'Wall-mounted / Cassette',
      recommendedSizeMy: 'Dinding / Kaset',
      price: 50,
      isPopular: false,
    },
    {
      id: 'standard',
      name: 'Standard AC Service',
      nameMy: 'Servis AC Standard',
      icon: Wind,
      desc: 'Basic maintenance for cooling',
      descMy: 'Penyelenggaraan asas untuk penyejukan',
      scope: 'Filter washing and basic clearing.',
      scopeMy: 'Basuh penapis dan pembersihan asas.',
      inclusions: ['Filter wash', 'Coil dust-off', 'Drain pipe clearing', 'Performance check'],
      inclusionsMy: ['Basuh penapis', 'Buang habuk gegelung', 'Bersihkan paip saliran', 'Semakan prestasi'],
      duration: '45 mins',
      durationMy: '45 minit',
      recommendedSize: 'Wall-mounted 1.0 - 2.0 HP',
      recommendedSizeMy: 'Dinding 1.0 - 2.0 HP',
      price: 59,
      isPopular: false,
    },
    {
      id: 'chemical',
      name: 'Chemical Wash',
      nameMy: 'Cucian Kimia',
      icon: FlaskConical,
      desc: 'Deep clean for better airflow',
      descMy: 'Pembersihan mendalam untuk aliran udara lebih baik',
      scope: 'Intensive chemical wash to remove stubborn dirt.',
      scopeMy: 'Cucian kimia intensif untuk menyingkirkan kotoran degil.',
      inclusions: ['Chemical spray on coils', 'Blower cleaning', 'Drain pipe flushing', 'Anti-bacterial wipe'],
      inclusionsMy: ['Semburan kimia pada gegelung', 'Pembersihan kipas blower', 'Cucian paip saliran', 'Lap anti-bakteria'],
      duration: '1.5 hours',
      durationMy: '1.5 jam',
      recommendedSize: 'AC not serviced > 6 months',
      recommendedSizeMy: 'AC tidak diservis > 6 bulan',
      price: 129,
      isPopular: true,
    },
    {
      id: 'overhaul',
      name: 'Chemical Overhaul',
      nameMy: 'Overhaul Kimia',
      icon: Wrench,
      desc: 'Full dismantle and wash',
      descMy: 'Bongkar sepenuhnya dan cuci',
      scope: 'Complete breakdown of AC unit for deep chemical wash.',
      scopeMy: 'Bongkar sepenuhnya unit AC untuk cucian kimia mendalam.',
      inclusions: ['Dismantle unit', 'Chemical soak', 'Bearing check & lube', 'Gas level check'],
      inclusionsMy: ['Bongkar unit', 'Rendam kimia', 'Semak & minyakkan bearing', 'Semakan paras gas'],
      duration: '2-3 hours',
      durationMy: '2-3 jam',
      recommendedSize: 'Severely clogged AC',
      recommendedSizeMy: 'AC yang sangat tersumbat',
      price: 199,
      isPopular: false,
    },
    {
      id: 'gas',
      name: 'Gas Top-Up',
      nameMy: 'Tambah Gas',
      icon: Gauge,
      desc: 'Refrigerant refill (R32/R410A)',
      descMy: 'Isi semula gas penyejuk (R32/R410A)',
      scope: 'Restore cooling gas levels.',
      scopeMy: 'Pulihkan paras gas penyejukan.',
      inclusions: ['Pressure reading', 'Gas top-up', 'Leak visual check', 'Cooling test'],
      inclusionsMy: ['Bacaan tekanan', 'Tambah gas', 'Semakan kebocoran secara visual', 'Ujian penyejukan'],
      duration: '45 mins',
      durationMy: '45 minit',
      recommendedSize: 'Low cooling units',
      recommendedSizeMy: 'Unit kurang sejuk',
      price: 149,
      isPopular: false,
    },
    {
      id: 'repair',
      name: 'AC Repair',
      nameMy: 'Pembaikan AC',
      icon: Wrench,
      desc: 'Fix leaks, noise, or power issues',
      descMy: 'Baiki kebocoran, bunyi bising, atau masalah kuasa',
      scope: 'Targeted repair based on diagnosis.',
      scopeMy: 'Pembaikan bersasar berdasarkan diagnosis.',
      inclusions: ['Part replacement (cost separate)', 'Leak patching', 'Testing & commissioning'],
      inclusionsMy: ['Penggantian alat ganti (kos berasingan)', 'Tampal kebocoran', 'Ujian & pentauliahan'],
      duration: 'Variable',
      durationMy: 'Berubah-ubah',
      recommendedSize: 'Any broken AC',
      recommendedSizeMy: 'Sebarang AC rosak',
      price: 80,
      isPopular: false,
    },
  ],
  plumbing: [
    {
      id: 'leak',
      name: 'Leak Repair',
      nameMy: 'Pembaikan Kebocoran',
      icon: Droplets,
      desc: 'Fix dripping pipes or fixtures',
      descMy: 'Baiki paip atau kelengkapan yang menitis',
      scope: 'Identify and patch minor water leaks.',
      scopeMy: 'Kenal pasti dan tampal kebocoran air kecil.',
      inclusions: ['Diagnosis', 'Pipe patching / tightening', 'Water flow test', 'Workmanship warranty'],
      inclusionsMy: ['Diagnosis', 'Tampal / ketatkan paip', 'Ujian aliran air', 'Waranti mutu kerja'],
      duration: '1-2 hours',
      durationMy: '1-2 jam',
      recommendedSize: 'Visible leaks',
      recommendedSizeMy: 'Kebocoran yang kelihatan',
      price: 99,
      isPopular: true,
    },
    {
      id: 'pipe',
      name: 'Pipe Replacement',
      nameMy: 'Penggantian Paip',
      icon: Wrench,
      desc: 'Replace old or burst pipes',
      descMy: 'Ganti paip lama atau pecah',
      scope: 'Install new PVC, UPVC or copper pipes.',
      scopeMy: 'Pasang paip PVC, UPVC atau tembaga baharu.',
      inclusions: ['Remove old pipe', 'Install new pipe segment', 'Joint sealing', 'Pressure test'],
      inclusionsMy: ['Tanggal paip lama', 'Pasang segmen paip baharu', 'Pengedap sambungan', 'Ujian tekanan'],
      duration: '2-4 hours',
      durationMy: '2-4 jam',
      recommendedSize: 'Burst or rusted pipes',
      recommendedSizeMy: 'Paip pecah atau berkarat',
      price: 150,
      isPopular: false,
    },
    {
      id: 'faucet',
      name: 'Faucet / Tap Installation',
      nameMy: 'Pemasangan Paip Air / Pili',
      icon: Droplet,
      desc: 'Install or replace water taps',
      descMy: 'Pasang atau ganti pili air',
      scope: 'Standard tap or mixer replacement.',
      scopeMy: 'Penggantian pili atau pengadun standard.',
      inclusions: ['Remove old tap', 'Install new tap (client provided)', 'Teflon sealing', 'Leak test'],
      inclusionsMy: ['Tanggal pili lama', 'Pasang pili baharu (disediakan pelanggan)', 'Pengedap Teflon', 'Ujian kebocoran'],
      duration: '45 mins',
      durationMy: '45 minit',
      recommendedSize: 'Kitchen & Bathrooms',
      recommendedSizeMy: 'Dapur & Bilik Air',
      price: 69,
      isPopular: false,
    },
    {
      id: 'toilet',
      name: 'Toilet Repair',
      nameMy: 'Pembaikan Tandas',
      icon: Toilet,
      desc: 'Fix flush or install new bowl',
      descMy: 'Baiki flush atau pasang mangkuk baharu',
      scope: 'Cistern repairs or full bowl replacement.',
      scopeMy: 'Pembaikan tangki atau penggantian mangkuk penuh.',
      inclusions: ['Flush mechanism fix', 'Full seal replacement', 'Water level adjustment'],
      inclusionsMy: ['Baiki mekanisme flush', 'Penggantian pengedap penuh', 'Pelarasan paras air'],
      duration: '1-2 hours',
      durationMy: '1-2 jam',
      recommendedSize: 'Running toilets',
      recommendedSizeMy: 'Tandas yang mengalir',
      price: 120,
      isPopular: false,
    },
    {
      id: 'heater',
      name: 'Water Heater Repair',
      nameMy: 'Pembaikan Pemanas Air',
      icon: Flame,
      desc: 'Fix instant or storage heaters',
      descMy: 'Baiki pemanas air segera atau tangki',
      scope: 'Electrical/plumbing fix for heaters.',
      scopeMy: 'Pembaikan elektrik/paip untuk pemanas air.',
      inclusions: ['Element check', 'Leak fix', 'Thermostat adjustment', 'Safety test'],
      inclusionsMy: ['Semakan elemen', 'Baiki kebocoran', 'Pelarasan termostat', 'Ujian keselamatan'],
      duration: '1.5 hours',
      durationMy: '1.5 jam',
      recommendedSize: 'No hot water / Leaks',
      recommendedSizeMy: 'Tiada air panas / Kebocoran',
      price: 130,
      isPopular: false,
    },
    {
      id: 'drain',
      name: 'Drain Unclogging',
      nameMy: 'Nyahsumbat Saliran',
      icon: Pipette,
      desc: 'Clear blocked sinks or floor traps',
      descMy: 'Bersihkan sinki atau perangkap lantai tersumbat',
      scope: 'Remove blockages from pipes.',
      scopeMy: 'Buang sumbatan dari paip.',
      inclusions: ['Manual snaking', 'Chemical dissolving (if needed)', 'Flow test'],
      inclusionsMy: ['Cucuk paip manual', 'Pelarutan kimia (jika perlu)', 'Ujian aliran'],
      duration: '1 hour',
      durationMy: '1 jam',
      recommendedSize: 'Slow draining water',
      recommendedSizeMy: 'Air lambat mengalir',
      price: 89,
      isPopular: false,
    },
    {
      id: 'emergency-plumbing',
      name: 'Emergency Plumbing',
      nameMy: 'Paip Kecemasan',
      icon: AlertTriangle,
      desc: '24/7 urgent burst pipe fix',
      descMy: 'Pembaikan paip pecah segera 24/7',
      scope: 'Immediate dispatch for critical issues.',
      scopeMy: 'Penghantaran segera untuk masalah kritikal.',
      inclusions: ['90-min ETA', 'Main valve shutoff', 'Temporary or permanent fix', 'Priority routing'],
      inclusionsMy: ['ETA 90 minit', 'Tutup injap utama', 'Pembaikan sementara atau kekal', 'Laluan keutamaan'],
      duration: 'Variable',
      durationMy: 'Berubah-ubah',
      recommendedSize: 'Major flooding',
      recommendedSizeMy: 'Banjir teruk',
      price: 199,
      isPopular: false,
    },
  ],
  electrical: [
    {
      id: 'electrical-inspect',
      name: 'Electrical Inspection',
      nameMy: 'Pemeriksaan Elektrik',
      icon: Zap,
      desc: 'Diagnose tripping or wiring issues',
      descMy: 'Diagnosis masalah tripping atau pendawaian',
      scope: 'Fault finding and safety check.',
      scopeMy: 'Pengesanan kerosakan dan semakan keselamatan.',
      inclusions: ['DB board check', 'Circuit testing', 'Load calculation', 'Repair quote'],
      inclusionsMy: ['Semakan DB board', 'Ujian litar', 'Pengiraan beban', 'Sebut harga pembaikan'],
      duration: '1 hour',
      durationMy: '1 jam',
      recommendedSize: 'Tripping MCB/RCCB',
      recommendedSizeMy: 'MCB/RCCB tripping',
      price: 80,
      isPopular: false,
    },
    {
      id: 'socket',
      name: 'Socket Installation',
      nameMy: 'Pemasangan Soket',
      icon: Plug,
      desc: 'Install new power points',
      descMy: 'Pasang soket kuasa baharu',
      scope: 'Add or replace 13A/15A sockets.',
      scopeMy: 'Tambah atau ganti soket 13A/15A.',
      inclusions: ['Wiring extension (up to 3m)', 'Socket faceplate mounting', 'Earth loop test'],
      inclusionsMy: ['Sambungan pendawaian (sehingga 3m)', 'Pemasangan muka soket', 'Ujian gelung bumi'],
      duration: '1-2 hours',
      durationMy: '1-2 jam',
      recommendedSize: 'Per socket',
      recommendedSizeMy: 'Setiap soket',
      price: 90,
      isPopular: true,
    },
    {
      id: 'light',
      name: 'Light Installation',
      nameMy: 'Pemasangan Lampu',
      icon: Sparkles,
      desc: 'Install downlights or fixtures',
      descMy: 'Pasang downlight atau kelengkapan lampu',
      scope: 'Mounting and wiring of light fittings.',
      scopeMy: 'Pemasangan dan pendawaian kelengkapan lampu.',
      inclusions: ['Fixture mounting (client provided)', 'Wiring connection', 'Switch test'],
      inclusionsMy: ['Pemasangan kelengkapan (disediakan pelanggan)', 'Sambungan pendawaian', 'Ujian suis'],
      duration: '45 mins',
      durationMy: '45 minit',
      recommendedSize: 'Per light fixture',
      recommendedSizeMy: 'Setiap kelengkapan lampu',
      price: 60,
      isPopular: false,
    },
    {
      id: 'fan',
      name: 'Ceiling Fan Installation',
      nameMy: 'Pemasangan Kipas Siling',
      icon: Wind,
      desc: 'Install ceiling or wall fans',
      descMy: 'Pasang kipas siling atau dinding',
      scope: 'Safe mounting of fan units.',
      scopeMy: 'Pemasangan unit kipas yang selamat.',
      inclusions: ['Hook installation', 'Fan assembly', 'Balancing', 'Speed regulator setup'],
      inclusionsMy: ['Pemasangan cangkuk', 'Pemasangan kipas', 'Pengimbangan', 'Pelarasan pengawal kelajuan'],
      duration: '1.5 hours',
      durationMy: '1.5 jam',
      recommendedSize: 'Per fan',
      recommendedSizeMy: 'Setiap kipas',
      price: 75,
      isPopular: false,
    },
    {
      id: 'db-board',
      name: 'DB Board Service',
      nameMy: 'Servis DB Board',
      icon: Zap,
      desc: 'Replace or upgrade distribution board',
      descMy: 'Ganti atau naik taraf DB board',
      scope: 'Main electrical panel works.',
      scopeMy: 'Kerja panel elektrik utama.',
      inclusions: ['Breaker replacement', 'Load balancing', 'Cable tidying', 'Full safety test'],
      inclusionsMy: ['Penggantian breaker', 'Pengimbangan beban', 'Kemas kabel', 'Ujian keselamatan penuh'],
      duration: '3-5 hours',
      durationMy: '3-5 jam',
      recommendedSize: 'Old or unsafe boards',
      recommendedSizeMy: 'Board lama atau tidak selamat',
      price: 350,
      isPopular: false,
    },
    {
      id: 'wiring',
      name: 'Wiring Repair',
      nameMy: 'Pembaikan Pendawaian',
      icon: Plug,
      desc: 'Fix burnt or faulty wiring',
      descMy: 'Baiki pendawaian terbakar atau rosak',
      scope: 'Replace damaged cables.',
      scopeMy: 'Ganti kabel yang rosak.',
      inclusions: ['Fault tracing', 'Cable replacement', 'Conduit fixing', 'Continuity test'],
      inclusionsMy: ['Pengesanan kerosakan', 'Penggantian kabel', 'Pembaikan konduit', 'Ujian kesinambungan'],
      duration: 'Variable',
      durationMy: 'Berubah-ubah',
      recommendedSize: 'Burnt smell / sparks',
      recommendedSizeMy: 'Bau hangit / percikan api',
      price: 150,
      isPopular: false,
    },
    {
      id: 'emergency-electrical',
      name: 'Emergency Electrical Service',
      nameMy: 'Servis Elektrik Kecemasan',
      icon: AlertTriangle,
      desc: '24/7 total blackout assistance',
      descMy: 'Bantuan blackout menyeluruh 24/7',
      scope: 'Urgent restoration of power.',
      scopeMy: 'Pemulihan kuasa segera.',
      inclusions: ['90-min ETA', 'TNB coordination (if needed)', 'Temporary power bypass', 'Priority routing'],
      inclusionsMy: ['ETA 90 minit', 'Penyelarasan TNB (jika perlu)', 'Pintasan kuasa sementara', 'Laluan keutamaan'],
      duration: 'Variable',
      durationMy: 'Berubah-ubah',
      recommendedSize: 'Total power loss',
      recommendedSizeMy: 'Kehilangan kuasa sepenuhnya',
      price: 200,
      isPopular: false,
    },
  ],
  painting: [
    {
      id: 'room',
      name: 'Room Painting',
      nameMy: 'Mengecat Bilik',
      icon: Brush,
      desc: 'Paint a single bedroom',
      descMy: 'Cat satu bilik tidur',
      scope: 'Wall and ceiling painting for one room.',
      scopeMy: 'Mengecat dinding dan siling untuk satu bilik.',
      inclusions: ['Floor protection', 'Minor crack patching', '1 coat primer (optional)', '2 coats paint'],
      inclusionsMy: ['Perlindungan lantai', 'Tampal rekahan kecil', '1 lapis primer (pilihan)', '2 lapis cat'],
      duration: '1 day',
      durationMy: '1 hari',
      recommendedSize: 'Up to 150 sqft',
      recommendedSizeMy: 'Sehingga 150 kps',
      price: 350,
      isPopular: false,
    },
    {
      id: 'interior',
      name: 'Interior Painting',
      nameMy: 'Mengecat Dalaman',
      icon: Home,
      desc: 'Full house interior',
      descMy: 'Dalaman rumah sepenuhnya',
      scope: 'Complete interior walls and ceilings.',
      scopeMy: 'Dinding dalaman dan siling sepenuhnya.',
      inclusions: ['Furniture covering', 'Wall prep & sanding', '2 coats emulsion paint', 'Post-paint cleanup'],
      inclusionsMy: ['Penutupan perabot', 'Sediakan & ampelas dinding', '2 lapis cat emulsi', 'Pembersihan selepas mengecat'],
      duration: '3-5 days',
      durationMy: '3-5 hari',
      recommendedSize: 'Living + Bedrooms',
      recommendedSizeMy: 'Ruang tamu + Bilik tidur',
      price: 1200,
      isPopular: true,
    },
    {
      id: 'exterior',
      name: 'Exterior Painting',
      nameMy: 'Mengecat Luaran',
      icon: Building,
      desc: 'Weather-resistant exterior coat',
      descMy: 'Lapisan luaran tahan cuaca',
      scope: 'Outer walls and facades.',
      scopeMy: 'Dinding luar dan fasad.',
      inclusions: ['High-pressure wash prep', 'Fungus wash', 'Weatherbond primer', '2 coats exterior paint'],
      inclusionsMy: ['Cucian tekanan tinggi', 'Cucian kulat', 'Primer tahan cuaca', '2 lapis cat luaran'],
      duration: '4-7 days',
      durationMy: '4-7 hari',
      recommendedSize: 'Landed properties',
      recommendedSizeMy: 'Hartanah bertanah',
      price: 2500,
      isPopular: false,
    },
    {
      id: 'condo',
      name: 'Condo Repainting',
      nameMy: 'Mengecat Semula Kondo',
      icon: Building,
      desc: 'Specialized for high-rises',
      descMy: 'Khusus untuk bangunan tinggi',
      scope: 'Interior painting compliant with condo rules.',
      scopeMy: 'Mengecat dalaman mengikut peraturan kondo.',
      inclusions: ['Management permit assistance', 'Common area protection', 'Odorless paint options'],
      inclusionsMy: ['Bantuan permit pengurusan', 'Perlindungan kawasan umum', 'Pilihan cat tanpa bau'],
      duration: '2-4 days',
      durationMy: '2-4 hari',
      recommendedSize: '800 - 1500 sqft',
      recommendedSizeMy: '800 - 1500 kps',
      price: 1500,
      isPopular: false,
    },
    {
      id: 'premium-paint',
      name: 'Premium Paint Package',
      nameMy: 'Pakej Cat Premium',
      icon: Sparkles,
      desc: 'Washable, anti-bacterial finish',
      descMy: 'Kemasan boleh cuci, anti-bakteria',
      scope: 'High-end paint application.',
      scopeMy: 'Aplikasi cat berkualiti tinggi.',
      inclusions: ['Premium brand paint (e.g. Nippon Odour-less)', 'Flawless wall skimming', 'Color consultation'],
      inclusionsMy: ['Cat jenama premium (cth. Nippon Odour-less)', 'Skimming dinding sempurna', 'Perundingan warna'],
      duration: '4-6 days',
      durationMy: '4-6 hari',
      recommendedSize: 'Luxury homes',
      recommendedSizeMy: 'Rumah mewah',
      price: 3000,
      isPopular: false,
    },
  ],
  'pest-control': [
    {
      id: 'general-pest',
      name: 'General Pest Treatment',
      nameMy: 'Rawatan Perosak Am',
      icon: Bug,
      desc: 'Routine spraying for common pests',
      descMy: 'Semburan rutin untuk perosak biasa',
      scope: 'Preventative surface spray.',
      scopeMy: 'Semburan permukaan pencegahan.',
      inclusions: ['Perimeter spraying', 'Targeted crack & crevice treatment', 'Basic baiting'],
      inclusionsMy: ['Semburan perimeter', 'Rawatan bersasar pada rekahan & celah', 'Umpan asas'],
      duration: '1 hour',
      durationMy: '1 jam',
      recommendedSize: 'Apartments / Condos',
      recommendedSizeMy: 'Apartmen / Kondo',
      price: 99,
      isPopular: true,
    },
    {
      id: 'cockroach',
      name: 'Cockroach Treatment',
      nameMy: 'Rawatan Lipas',
      icon: Bug,
      desc: 'Eradicate roach infestations',
      descMy: 'Hapuskan serangan lipas',
      scope: 'Intensive baiting and flushing.',
      scopeMy: 'Umpan intensif dan pembilasan.',
      inclusions: ['Gel bait application', 'Flushing chemicals in drains', 'Kitchen cabinet treatment'],
      inclusionsMy: ['Sapuan umpan gel', 'Pembilasan kimia dalam saliran', 'Rawatan kabinet dapur'],
      duration: '1.5 hours',
      durationMy: '1.5 jam',
      recommendedSize: 'Active infestation',
      recommendedSizeMy: 'Serangan aktif',
      price: 150,
      isPopular: false,
    },
    {
      id: 'termite-inspect',
      name: 'Termite Inspection',
      nameMy: 'Pemeriksaan Anai-Anai',
      icon: ShieldCheck,
      desc: 'Detect termite activity',
      descMy: 'Kesan aktiviti anai-anai',
      scope: 'Professional assessment using scanners.',
      scopeMy: 'Penilaian profesional menggunakan pengimbas.',
      inclusions: ['Thermal imaging scan', 'Moisture meter check', 'Comprehensive report', 'Treatment quote'],
      inclusionsMy: ['Imbasan pengimejan terma', 'Semakan meter kelembapan', 'Laporan menyeluruh', 'Sebut harga rawatan'],
      duration: '1.5 hours',
      durationMy: '1.5 jam',
      recommendedSize: 'Landed properties',
      recommendedSizeMy: 'Hartanah bertanah',
      price: 120,
      isPopular: false,
    },
    {
      id: 'termite-treat',
      name: 'Termite Treatment',
      nameMy: 'Rawatan Anai-Anai',
      icon: Hammer,
      desc: 'Soil treatment or baiting system',
      descMy: 'Rawatan tanah atau sistem umpan',
      scope: 'Eliminate termite colonies.',
      scopeMy: 'Hapuskan koloni anai-anai.',
      inclusions: ['Drilling & chemical injection OR Baiting station setup', 'Colony elimination guarantee', 'Warranty certificate'],
      inclusionsMy: ['Gerudi & suntikan kimia ATAU pemasangan stesen umpan', 'Jaminan penghapusan koloni', 'Sijil waranti'],
      duration: '1 day',
      durationMy: '1 hari',
      recommendedSize: 'Active termite damage',
      recommendedSizeMy: 'Kerosakan anai-anai aktif',
      price: 1500,
      isPopular: false,
    },
    {
      id: 'rodent',
      name: 'Rodent Control',
      nameMy: 'Kawalan Tikus',
      icon: Bug,
      desc: 'Rat and mouse trapping',
      descMy: 'Perangkap tikus besar dan kecil',
      scope: 'Baiting and exclusion work.',
      scopeMy: 'Kerja umpan dan penyekatan.',
      inclusions: ['Trap placement', 'Entry point sealing', 'Carcass removal (follow-up)'],
      inclusionsMy: ['Pemasangan perangkap', 'Pengedapan titik masuk', 'Penyingkiran bangkai (susulan)'],
      duration: '2 visits',
      durationMy: '2 lawatan',
      recommendedSize: 'Ceiling noises / droppings',
      recommendedSizeMy: 'Bunyi siling / najis tikus',
      price: 250,
      isPopular: false,
    },
    {
      id: 'mosquito',
      name: 'Mosquito Treatment',
      nameMy: 'Rawatan Nyamuk',
      icon: Wind,
      desc: 'Fogging and larvicide',
      descMy: 'Fogging dan larvisid',
      scope: 'Outdoor mosquito eradication.',
      scopeMy: 'Penghapusan nyamuk luar.',
      inclusions: ['Thermal fogging', 'Larvicide in stagnant water', 'Drainage inspection'],
      inclusionsMy: ['Fogging terma', 'Larvisid dalam air bertakung', 'Pemeriksaan saliran'],
      duration: '1 hour',
      durationMy: '1 jam',
      recommendedSize: 'Gardens / Outdoors',
      recommendedSizeMy: 'Taman / Luar rumah',
      price: 180,
      isPopular: false,
    },
  ]
};

export const CATEGORY_ADDONS = {
  cleaning: [
    { id: 'extra_bathroom', label: 'Extra Bathroom', labelMy: 'Bilik Air Tambahan', price: 25 },
    { id: 'window', label: 'Window Cleaning', labelMy: 'Pembersihan Tingkap', price: 40 },
    { id: 'carpet', label: 'Carpet Vacuum', labelMy: 'Vakum Karpet', price: 30 },
    { id: 'ironing', label: 'Ironing (20 items)', labelMy: 'Seterika (20 helai)', price: 35 },
  ],
  ac: [
    { id: 'antibac', label: 'Anti-bacterial coating', labelMy: 'Salutan anti-bakteria', price: 39 },
    { id: 'drain_pipe', label: 'Drain pipe replacement', labelMy: 'Penggantian paip saliran', price: 49 },
    { id: 'remote', label: 'Remote replacement', labelMy: 'Penggantian alat kawalan jauh', price: 55 },
  ],
  plumbing: [
    { id: 'braided_hose', label: 'Braided hose replacement', labelMy: 'Penggantian hos berjalin', price: 25 },
    { id: 'warranty1y', label: '1-yr leak warranty', labelMy: 'Waranti kebocoran 1 tahun', price: 49 },
    { id: 'patching', label: 'Wall patching', labelMy: 'Tampalan dinding', price: 45 },
  ],
  electrical: [
    { id: 'cable', label: 'Extra cable (per meter)', labelMy: 'Kabel tambahan (setiap meter)', price: 15 },
    { id: 'casing', label: 'PVC casing', labelMy: 'Penutup PVC', price: 20 },
  ],
  painting: [
    { id: 'primer', label: 'Apply 1 coat primer', labelMy: 'Sapukan 1 lapis primer', price: 200 },
    { id: 'doors', label: 'Paint 3 interior doors', labelMy: 'Cat 3 pintu dalaman', price: 150 },
  ],
  'pest-control': [
    { id: 'extra_bait', label: 'Extra gel baits', labelMy: 'Umpan gel tambahan', price: 30 },
    { id: 'followup', label: 'Follow-up visit (14 days)', labelMy: 'Lawatan susulan (14 hari)', price: 80 },
  ]
};

export function getPackages(serviceId) {
  const norm = serviceId === 'home-cleaning' ? 'cleaning' : 
               serviceId === 'ac-servicing' ? 'ac' : serviceId;
  return CATEGORY_PACKAGES[norm] || CATEGORY_PACKAGES.cleaning;
}

export function getAddons(serviceId) {
  const norm = serviceId === 'home-cleaning' ? 'cleaning' : 
               serviceId === 'ac-servicing' ? 'ac' : serviceId;
  return CATEGORY_ADDONS[norm] || CATEGORY_ADDONS.cleaning;
}
