// src/lib/catalog/cleaning.js
export const cleaningCategory = {
  id: 'cleaning',
  slug: 'cleaning',
  name: 'Home Cleaning',
  nameMy: 'Pembersihan Rumah',
  tagline: 'Vetted cleaners, spotless homes.',
  taglineMy: 'Pembersih bertauliah, rumah bersinar.',
  iconKey: 'Sparkles',
  accent: 'emerald',
  heroImage: '/img/category/cleaning.webp',
  priceFrom: 89,
  emergencySupported: false,
  recurringSupported: true,
  subcategories: [
    { id: 'general',      name: 'General Clean',     nameMy: 'Pembersihan Am',         iconKey: 'Sparkles' },
    { id: 'deep',         name: 'Deep Clean',        nameMy: 'Pembersihan Mendalam',   iconKey: 'Droplets' },
    { id: 'move',         name: 'Move In / Out',     nameMy: 'Masuk / Keluar Rumah',   iconKey: 'Truck' },
    { id: 'post-reno',    name: 'Post-Renovation',   nameMy: 'Selepas Renovasi',       iconKey: 'Hammer' },
    { id: 'sofa',         name: 'Sofa & Upholstery', nameMy: 'Sofa & Kusyen',          iconKey: 'Sofa' },
    { id: 'mattress',     name: 'Mattress',          nameMy: 'Tilam',                  iconKey: 'Bed' },
    { id: 'disinfection', name: 'Disinfection',      nameMy: 'Disinfeksi',             iconKey: 'ShieldCheck' },
  ],
};

export const cleaningPackages = [
  {
    id: 'essential', name: 'Essential', nameMy: 'Asas',
    tagline: 'Standard professional clean', multiplier: 1.0,
    inclusions: [
      'Dust + vacuum all rooms',
      'Mop all hard floors',
      'Clean all bathrooms',
      'Kitchen surface wipe-down',
      'Bedding straighten',
      'Empty trash bins',
    ],
  },
  {
    id: 'signature', name: 'Signature', nameMy: 'Pilihan',
    tagline: 'Most chosen · deep + detail', multiplier: 1.5,
    inclusions: [
      'Everything in Essential',
      'Inside cabinets',
      'Appliance exteriors',
      'Glass + mirrors polish',
      'Light fixture dusting',
      'Skirting + door frames',
    ],
  },
  {
    id: 'premium', name: 'Premium', nameMy: 'Premium',
    tagline: 'White-glove finish · 7-day guarantee', multiplier: 2.1,
    warrantyDays: 7,
    inclusions: [
      'Everything in Signature',
      'Inside fridge + oven',
      'Linen change',
      'Aroma finish',
      'Eco-friendly chemicals',
      '7-day re-clean guarantee',
    ],
  },
];

export const cleaningAddons = [
  { id: 'fridge_inside', name: 'Inside fridge',      nameMy: 'Dalam peti sejuk', price: 35, duration_min: 25 },
  { id: 'oven_inside',   name: 'Inside oven',        nameMy: 'Dalam ketuhar',    price: 40, duration_min: 30 },
  { id: 'balcony',       name: 'Balcony deep clean', nameMy: 'Balkoni',          price: 30, duration_min: 25 },
  { id: 'window_ext',    name: 'Window exterior',    nameMy: 'Tingkap luaran',   price: 45, duration_min: 30 },
  { id: 'ironing20',     name: 'Ironing (20 pcs)',   nameMy: 'Seterika 20 helai',price: 35, duration_min: 35 },
  { id: 'eco',           name: 'Eco-friendly pack',  nameMy: 'Mesra alam',       price: 25, duration_min: 0  },
];

const ALL_PACKAGES = ['essential', 'signature', 'premium'];
const ALL_ADDONS   = cleaningAddons.map((a) => a.id);
const KL_AREAS = ['Kuala Lumpur', 'Petaling Jaya', 'Shah Alam', 'Subang Jaya', 'Ampang', 'Cheras', 'Bangsar', 'Mont Kiara'];

export const cleaningServices = [
  {
    id: 'cleaning.general.studio', slug: 'general-studio',
    categoryId: 'cleaning', subcategoryId: 'general',
    name: 'General Clean — Studio / 1BR', nameMy: 'Pembersihan Am — Studio / 1BR',
    description: 'Standard clean for studios and 1-bedroom units.',
    descriptionMy: 'Pembersihan asas untuk studio dan unit 1 bilik.',
    basePrice: 89, duration_min: 90, duration_max: 150,
    packages: ALL_PACKAGES, addons: ALL_ADDONS,
    propertyTypes: ['studio', 'condo', 'apartment'],
    bookingModes: ['oneoff', 'recurring'],
    cities: KL_AREAS,
    partnerSkills: ['certified_cleaner'], tools: ['vacuum_hepa', 'microfiber_set', 'mop_system'],
    safetyChecks: ['before_photos', 'checklist_confirm', 'after_photos'],
  },
  {
    id: 'cleaning.general.2br-condo', slug: 'general-2br-condo',
    categoryId: 'cleaning', subcategoryId: 'general',
    name: 'General Clean — 2BR Condo', nameMy: 'Pembersihan Am — Kondo 2BR',
    description: 'Standard clean for 2-bedroom condominiums.',
    descriptionMy: 'Pembersihan asas untuk kondominium 2 bilik.',
    basePrice: 119, duration_min: 120, duration_max: 180,
    packages: ALL_PACKAGES, addons: ALL_ADDONS,
    propertyTypes: ['condo', 'apartment'], bookingModes: ['oneoff', 'recurring'],
    cities: KL_AREAS, partnerSkills: ['certified_cleaner'],
    tools: ['vacuum_hepa', 'microfiber_set', 'mop_system'],
    safetyChecks: ['before_photos', 'checklist_confirm', 'after_photos'],
  },
  {
    id: 'cleaning.general.3br-condo', slug: 'general-3br-condo',
    categoryId: 'cleaning', subcategoryId: 'general',
    name: 'General Clean — 3BR Condo', nameMy: 'Pembersihan Am — Kondo 3BR',
    description: 'Standard clean for 3-bedroom condominiums.',
    descriptionMy: 'Pembersihan asas untuk kondominium 3 bilik.',
    basePrice: 149, duration_min: 180, duration_max: 240,
    packages: ALL_PACKAGES, addons: ALL_ADDONS,
    propertyTypes: ['condo', 'apartment'], bookingModes: ['oneoff', 'recurring'],
    cities: KL_AREAS, partnerSkills: ['certified_cleaner'],
    tools: ['vacuum_hepa', 'microfiber_set', 'mop_system'],
    safetyChecks: ['before_photos', 'checklist_confirm', 'after_photos'],
  },
  {
    id: 'cleaning.general.landed-4br', slug: 'general-landed-4br',
    categoryId: 'cleaning', subcategoryId: 'general',
    name: 'General Clean — Landed 4BR', nameMy: 'Pembersihan Am — Banglo 4BR',
    description: 'Standard clean for 4-bedroom landed homes.',
    descriptionMy: 'Pembersihan asas untuk rumah teres / banglo 4 bilik.',
    basePrice: 199, duration_min: 240, duration_max: 300,
    packages: ALL_PACKAGES, addons: ALL_ADDONS,
    propertyTypes: ['landed'], bookingModes: ['oneoff', 'recurring'],
    cities: KL_AREAS, partnerSkills: ['certified_cleaner'],
    tools: ['vacuum_hepa', 'microfiber_set', 'mop_system', 'ladder_3m'],
    safetyChecks: ['before_photos', 'checklist_confirm', 'after_photos'],
  },
  {
    id: 'cleaning.deep.3br', slug: 'deep-3br',
    categoryId: 'cleaning', subcategoryId: 'deep',
    name: 'Deep Clean — 3BR', nameMy: 'Pembersihan Mendalam — 3BR',
    description: 'Top-to-bottom deep clean for 3-bedroom homes.',
    descriptionMy: 'Pembersihan menyeluruh untuk rumah 3 bilik.',
    basePrice: 299, duration_min: 270, duration_max: 360,
    packages: ALL_PACKAGES, addons: ALL_ADDONS,
    propertyTypes: ['condo', 'apartment', 'landed'], bookingModes: ['oneoff'],
    cities: KL_AREAS,
    partnerSkills: ['certified_cleaner', 'deep_clean_certified'],
    tools: ['vacuum_hepa', 'microfiber_set', 'mop_system', 'steam_cleaner'],
    safetyChecks: ['before_photos', 'checklist_confirm', 'after_photos', 'walkthrough'],
  },
  {
    id: 'cleaning.move.in-out', slug: 'move-in-out',
    categoryId: 'cleaning', subcategoryId: 'move',
    name: 'Move-in / Move-out Clean', nameMy: 'Pembersihan Masuk / Keluar',
    description: 'Full empty-home clean for handover or move-in.',
    descriptionMy: 'Pembersihan rumah kosong untuk serahan atau masuk.',
    basePrice: 349, duration_min: 300, duration_max: 480,
    packages: ALL_PACKAGES, addons: ALL_ADDONS,
    propertyTypes: ['condo', 'apartment', 'landed'], bookingModes: ['oneoff'],
    cities: KL_AREAS, partnerSkills: ['certified_cleaner', 'deep_clean_certified'],
    tools: ['vacuum_hepa', 'microfiber_set', 'mop_system'],
    safetyChecks: ['before_photos', 'checklist_confirm', 'after_photos', 'walkthrough'],
  },
  {
    id: 'cleaning.sofa.3seater', slug: 'sofa-3seater',
    categoryId: 'cleaning', subcategoryId: 'sofa',
    name: 'Sofa Cleaning — 3-seater', nameMy: 'Pembersihan Sofa — 3-tempat duduk',
    description: 'Fabric or leather sofa deep clean.',
    descriptionMy: 'Pembersihan sofa kain atau kulit.',
    basePrice: 119, duration_min: 60, duration_max: 90,
    packages: ['essential', 'signature'], addons: [],
    propertyTypes: ['condo', 'apartment', 'landed'], bookingModes: ['oneoff'],
    cities: KL_AREAS, partnerSkills: ['upholstery_cleaner'],
    tools: ['extraction_machine', 'upholstery_chems'],
    safetyChecks: ['before_photos', 'after_photos'],
  },
  {
    id: 'cleaning.mattress.queen', slug: 'mattress-queen',
    categoryId: 'cleaning', subcategoryId: 'mattress',
    name: 'Mattress Cleaning — Queen', nameMy: 'Pembersihan Tilam — Queen',
    description: 'UV + extraction clean for queen mattresses.',
    descriptionMy: 'Pembersihan UV + sedutan untuk tilam queen.',
    basePrice: 99, duration_min: 40, duration_max: 60,
    packages: ['essential', 'signature'], addons: [],
    propertyTypes: ['condo', 'apartment', 'landed'], bookingModes: ['oneoff'],
    cities: KL_AREAS, partnerSkills: ['upholstery_cleaner'],
    tools: ['uv_wand', 'extraction_machine'],
    safetyChecks: ['before_photos', 'after_photos'],
  },
];
