// src/lib/catalog/plumbing.js
export const plumbingCategory = {
  id: 'plumbing',
  slug: 'plumbing',
  name: 'Plumbing',
  nameMy: 'Paip Air',
  tagline: 'Licensed plumbers, lasting fixes.',
  taglineMy: 'Tukang paip berlesen, baikan tahan lama.',
  iconKey: 'Droplets',
  accent: 'sky',
  heroImage: '/img/category/plumbing.webp',
  priceFrom: 69,
  emergencySupported: true,
  recurringSupported: false,
  subcategories: [
    { id: 'tap',         name: 'Tap & Mixer',     nameMy: 'Paip & Penyebar',     iconKey: 'Droplet' },
    { id: 'leak',        name: 'Leak Repair',     nameMy: 'Baikan Kebocoran',    iconKey: 'Droplets' },
    { id: 'toilet',      name: 'Toilet',          nameMy: 'Tandas',              iconKey: 'Toilet' },
    { id: 'drain',       name: 'Drain Unclog',    nameMy: 'Buka Sumbatan',       iconKey: 'Pipette' },
    { id: 'heater',      name: 'Water Heater',    nameMy: 'Pemanas Air',         iconKey: 'Flame' },
    { id: 'tank',        name: 'Water Tank',      nameMy: 'Tangki Air',          iconKey: 'Container' },
    { id: 'emergency',   name: 'Emergency Burst', nameMy: 'Kecemasan Paip',      iconKey: 'AlertTriangle' },
  ],
};

export const plumbingPackages = [
  { id: 'essential', name: 'Essential', nameMy: 'Asas',    tagline: 'Standard repair',  multiplier: 1.0,
    inclusions: ['Diagnosis', 'Repair', 'Function test', '7-day workmanship warranty'] },
  { id: 'signature', name: 'Signature', nameMy: 'Pilihan', tagline: 'Repair + premium parts', multiplier: 1.5,
    inclusions: ['Everything in Essential', 'Branded parts', '30-day warranty'] },
  { id: 'premium',   name: 'Premium',   nameMy: 'Premium', tagline: '1-year warranty', multiplier: 2.0, warrantyDays: 365,
    inclusions: ['Everything in Signature', 'Pressure test', 'Full inspection report', '1-year warranty'] },
];

export const plumbingAddons = [
  { id: 'braided_hose', name: 'Braided hose',     nameMy: 'Hos berkalut',     price: 25, duration_min: 5 },
  { id: 'mineral',      name: 'Mineral filter',   nameMy: 'Penapis mineral',  price: 89, duration_min: 20 },
  { id: 'warranty1y',   name: '1-yr leak warranty', nameMy: 'Waranti bocor 1 tahun', price: 49, duration_min: 0 },
  { id: 'patching',     name: 'Wall patching',    nameMy: 'Tampal dinding',   price: 45, duration_min: 25 },
];

const KL = ['Kuala Lumpur', 'Petaling Jaya', 'Shah Alam', 'Subang Jaya', 'Ampang', 'Cheras', 'Bangsar', 'Mont Kiara'];
const ALL_PKG = ['essential', 'signature', 'premium'];

export const plumbingServices = [
  {
    id: 'plumbing.tap.replace', slug: 'tap-replace',
    categoryId: 'plumbing', subcategoryId: 'tap',
    name: 'Tap Replacement', nameMy: 'Tukar Paip',
    description: 'Replace tap or mixer, function test included.',
    descriptionMy: 'Tukar paip atau penyebar, ujian fungsi termasuk.',
    basePrice: 69, duration_min: 30, duration_max: 60,
    packages: ALL_PKG, addons: ['braided_hose'],
    propertyTypes: ['condo', 'apartment', 'landed', 'office'], bookingModes: ['oneoff', 'emergency'],
    cities: KL, partnerSkills: ['span_licensed'],
    tools: ['pipe_wrench', 'teflon_tape', 'basin_wrench'],
    safetyChecks: ['shutoff_valve_photo', 'pressure_test', 'after_photos'],
  },
  {
    id: 'plumbing.leak.minor', slug: 'leak-minor',
    categoryId: 'plumbing', subcategoryId: 'leak',
    name: 'Leak Diagnosis + Fix (minor)', nameMy: 'Diagnosis & Baikan Kebocoran (kecil)',
    description: 'Locate and fix minor leaks.',
    descriptionMy: 'Cari dan baiki kebocoran kecil.',
    basePrice: 99, duration_min: 45, duration_max: 75,
    packages: ALL_PKG, addons: ['warranty1y', 'patching'],
    propertyTypes: ['condo', 'apartment', 'landed', 'office'], bookingModes: ['oneoff', 'emergency'],
    cities: KL, partnerSkills: ['span_licensed'],
    tools: ['leak_detector', 'pipe_wrench', 'soldering_kit'],
    safetyChecks: ['shutoff_valve_photo', 'meter_reading_pre', 'meter_reading_post'],
  },
  {
    id: 'plumbing.toilet.install', slug: 'toilet-install',
    categoryId: 'plumbing', subcategoryId: 'toilet',
    name: 'Toilet Bowl Installation', nameMy: 'Pemasangan Mangkuk Tandas',
    description: 'Install or replace toilet bowl, full seal + test.',
    descriptionMy: 'Pasang atau tukar mangkuk tandas, seal penuh + ujian.',
    basePrice: 149, duration_min: 75, duration_max: 120,
    packages: ALL_PKG, addons: ['patching'],
    propertyTypes: ['condo', 'apartment', 'landed', 'office'], bookingModes: ['oneoff'],
    cities: KL, partnerSkills: ['span_licensed'],
    tools: ['pipe_wrench', 'silicone_gun', 'wax_ring'],
    safetyChecks: ['shutoff_valve_photo', 'flush_test', 'leak_test'],
  },
  {
    id: 'plumbing.drain.unclog', slug: 'drain-unclog',
    categoryId: 'plumbing', subcategoryId: 'drain',
    name: 'Drain Unclog (kitchen / bath)', nameMy: 'Buka Sumbatan (dapur / bilik air)',
    description: 'Unclog blocked drains with auger.',
    descriptionMy: 'Buka sumbatan saluran dengan auger.',
    basePrice: 89, duration_min: 40, duration_max: 75,
    packages: ALL_PKG, addons: [],
    propertyTypes: ['condo', 'apartment', 'landed', 'office'], bookingModes: ['oneoff', 'emergency'],
    cities: KL, partnerSkills: ['span_licensed'],
    tools: ['snake_auger_3m', 'snake_auger_10m'],
    safetyChecks: ['before_photos', 'flow_test', 'after_photos'],
  },
  {
    id: 'plumbing.heater.storage', slug: 'heater-storage',
    categoryId: 'plumbing', subcategoryId: 'heater',
    name: 'Water Heater Install (storage)', nameMy: 'Pemasangan Pemanas Air (simpanan)',
    description: 'Install storage-tank water heater.',
    descriptionMy: 'Pemasangan pemanas air jenis tangki.',
    basePrice: 199, duration_min: 90, duration_max: 150,
    packages: ALL_PKG, addons: ['warranty1y'],
    propertyTypes: ['condo', 'apartment', 'landed'], bookingModes: ['oneoff'],
    cities: KL, partnerSkills: ['span_licensed', 'st_wireman'],
    tools: ['pipe_wrench', 'drill', 'multimeter'],
    safetyChecks: ['shutoff_valve_photo', 'rccb_test', 'after_photos'],
  },
  {
    id: 'plumbing.heater.instant', slug: 'heater-instant',
    categoryId: 'plumbing', subcategoryId: 'heater',
    name: 'Instant Heater Install', nameMy: 'Pemasangan Pemanas Segera',
    description: 'Install instant electric water heater.',
    descriptionMy: 'Pemasangan pemanas air segera.',
    basePrice: 149, duration_min: 60, duration_max: 90,
    packages: ALL_PKG, addons: ['warranty1y'],
    propertyTypes: ['condo', 'apartment', 'landed'], bookingModes: ['oneoff'],
    cities: KL, partnerSkills: ['span_licensed', 'st_wireman'],
    tools: ['pipe_wrench', 'drill', 'multimeter'],
    safetyChecks: ['shutoff_valve_photo', 'rccb_test', 'after_photos'],
  },
  {
    id: 'plumbing.tank.clean400', slug: 'tank-clean-400gal',
    categoryId: 'plumbing', subcategoryId: 'tank',
    name: 'Water Tank Clean — 400 gal', nameMy: 'Pencucian Tangki Air — 400 gal',
    description: 'Clean and disinfect 400-gallon water tank.',
    descriptionMy: 'Cuci dan disinfek tangki air 400 gelen.',
    basePrice: 249, duration_min: 90, duration_max: 150,
    packages: ['essential', 'signature'], addons: [],
    propertyTypes: ['landed'], bookingModes: ['oneoff'],
    cities: KL, partnerSkills: ['span_licensed', 'confined_space'],
    tools: ['pressure_washer', 'food_grade_disinfectant'],
    safetyChecks: ['before_photos', 'disinfectant_log', 'after_photos'],
  },
  {
    id: 'plumbing.emergency.burst', slug: 'emergency-burst',
    categoryId: 'plumbing', subcategoryId: 'emergency',
    name: 'Emergency Burst Pipe (24/7)', nameMy: 'Kecemasan Paip Pecah (24/7)',
    description: '90-min ETA in Klang Valley. Same-day fix.',
    descriptionMy: 'ETA 90 minit di Lembah Klang. Baikan hari sama.',
    basePrice: 199, duration_min: 60, duration_max: 180,
    packages: ['essential', 'signature', 'premium'], addons: ['warranty1y', 'patching'],
    propertyTypes: ['condo', 'apartment', 'landed', 'office'], bookingModes: ['emergency'],
    cities: KL, partnerSkills: ['span_licensed', 'emergency_certified'],
    tools: ['pipe_wrench', 'leak_detector', 'soldering_kit'],
    safetyChecks: ['shutoff_valve_photo', 'before_photos', 'pressure_test', 'after_photos'],
  },
];
